---
title: "Module 1, Part 3: Adverse Selection"
linktitle: "M1.3: Adverse Selection"
menu:
  content:
    parent: Module 1
    weight: 4
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

In Part 3, we'll broaden our study of insurance purchasing to the market level and study how the presence of adverse selection can affect insurance markets and premiums.

## Objectives
- Explain and draw graphically a simplified insurance market with adverse selection
- Calculate the insurer loss or profit at a given price
- Calculate the equilibrium price in the market under some assumptions on insurer profitability
- Solve for the subsidy amount or penalty amount that would ensure full insurance in a market
 
## Activities
- In-class problem on adverse selection. The worksheet is [here](/resource/wksheet3.html).


## Slides
Stay tuned for a shorter slide deck covering just part 3. In the meantime, please use the full slide deck on the [overview page](/content/01-content0/)