---
title: "Module 1, Part 4: Health Insurance Policy Discussion"
linktitle: "M1.4: Policy"
menu:
  content:
    parent: Module 1
    weight: 5
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

Part 4 concludes our study of health insurance. We'll finish this module with a discussion of some real world policy issues and some history of health insurance markets in the U.S.

## Objectives
- Explain the history of the employer-provided health insurance market in the U.S.
- Define community ratings and discuss its costs and benefits for insurance markets
- Define risk-adjustment and its relevance to insurance markets

## Activities
- Review Medicare Advantage and FFS data for Homework 1
- Discuss @mcwilliams2012. Link to paper [here](https://www.healthaffairs.org/doi/abs/10.1377/hlthaff.2011.1344)
- [Homework 1](/assignment/homework1.html) due this Friday!

### Supplemental Readings


## Slides
Stay tuned for a shorter slide deck covering just part 4. In the meantime, please use the full slide deck on the [overview page](/content/01-content0/)