---
title: "Module 2, Part 4: Policy Discussion"
linktitle: "M2.4: Policy"
menu:
  content:
    parent: Module 2
    weight: 5
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This final part of Module 2 concludes our discussion of physician agency. We'll talk about recent policy events including pay-for-performance and capitated payment models. We'll also discuss an academic paper in this area to help us practice reading and discussing this type of material.

## Objectives for this week
- Explain at least one recent hospital pay for performance program
- Identify and explain two pros and two cons from health care pay for performance models
- Define a capitated payment and describe at least one type of capitated payment currently in the U.S.
- Discuss the merits and drawbacks of a capitated payment model


## Activities
- Review homework 2
- Discuss [@clemens2014]. Link to paper [here](https://www.aeaweb.org/articles?id=10.1257/aer.104.4.1320).


## Slides
Stay tuned for a shorter slide deck covering just part 1. In the meantime, please use the full slide deck on the [overview page](/content/02-content4/)