---
title: "Module 2, Part 1: Introduction to Physician Agency"
linktitle: "M2.1: Agency Problem"
menu:
  content:
    parent: Module 2
    weight: 2
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

In part 1, we introduce the idea of physician agency and our study of physician treatment decisions. Just as asymmetric information between patients and insurance companies was a big part of the adverse selection problem, this module will show how asymmetric information between physicians and patients can also create some interesting dynamics and incentives.

## Objectives
- Explain the principal-agent problem in the context of medical care
- Solve for treatment levels when physicians set prices and quantity
 
## Activities
- In-class problem on physician agency. The worksheet is [here](/resource/wksheet4.html).

## Slides
Stay tuned for a shorter slide deck covering just part 1. In the meantime, please use the full slide deck on the [overview page](/content/02-content0/)