---
title: "Weekly Guide 4"
linktitle: "Week 4"
citeproc: true
bibliography: ../../static/bib/BibTeX_Library.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
menu:
  content:
    parent: Weekly Guides
    weight: 4
type: docs
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week we'll broaden our study of insurance purchasing to the market level and study how the presence of adverse selection can affect insurance markets and premiums.

### Objectives for this week
- Explain and draw graphically a simplified insurance market with adverse selection
- Calculate the insurer loss or profit at a given price
- Calculate the equilibrium price in the market under some assumptions on insurer profitability
- Solve for the subsidy amount or penalty amount that would ensure full insurance in a market
 

### Activities
- In-class problem on adverse selection. The worksheet is [here](/resource/wksheet3.html).
- [Slides on Health Insurance Trivia](https://docs.google.com/presentation/d/1tXKmoT0fjLrIPCgMYWg_SQZOWiQKuBmANvTnwBtjO5M/edit?usp=sharing)
- [Slides on ACA Exchange Pricing](https://docs.google.com/presentation/d/10oma6GyyympKxUx3pEQRUtCMLfJyHbrN6cDjQTw_woc/edit?usp=sharing)

### Supplemental readings
- Section 17.1 of [@pindyck2018]
- Chapter 4 of [@sloan2012]
- [@einav2011]. Link to paper [here](https://www.aeaweb.org/articles?id=10.1257/jep.25.1.115).
