---
title: "Weekly Guide 6"
linktitle: "Week 6"
menu:
  content:
    parent: Weekly Guides
    weight: 6
type: docs
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we'll move on from insurance markets and into physician treatment decisions. Just as asymmetric information between patients and insurance companies was a big part of the adverse selection problem, this module will show how asymmetric information between physicians and patients can also create some interesting dynamics and incentives.

### Objectives for this week
- Explain the principal-agent problem in the context of medical care
- Solve for treatment levels when physicians set prices and quantity
 

### Activities
- In-class problem on physician agency. The worksheet is [here](/resource/wksheet4.html).
- Weekly check-in on Friday

### Supplemental Readings
- Section 17.4 of [@pindyck2018]
- Sections 5.3 and 17.2 of [@sloan2012]
- [@mcguire2000]. Link to Chapter [here](https://www.sciencedirect.com/science/article/abs/pii/S1574006400801687)
- The Atlantic, December 2013, ["You're Getting Too Much Healthcare](https://www.theatlantic.com/health/archive/2013/12/youre-getting-too-much-healthcare/281896/)
- [Slides on physicians and financial incentives](https://docs.google.com/presentation/d/1mDrHqX3csv8nBaNSmmq5IHjq75E2k50mshLERnrEsfE/edit?usp=sharing)
- [Slides on physician agency and lower limb MRI](https://docs.google.com/presentation/d/1DXCjBHg4pDRn-cxudsEpYGLWYuBesZc6RguBXebrens/edit?usp=sharing)