---
title: "Homework 2"
linktitle: "Homework 2"
due_date: "2021-03-23"
due_time: "11:59 PM"
output:
  blogdown::html_page:
    toc: false
menu:
  assignment:
    parent: Homework
    weight: 2
type: docs
---

## Instructions
This is our second homework assignment of the semester. It covers questions related to physician treatment decisions and asymmetric information. 

## Theory Questions
1. Assume a physician is operating with the standard profit function, $\pi = (p-c)x$, where $c$ reflects a constant marginal cost of production, $x$ denotes quantity of healthcare provided, and $p$ denotes the price per unit of healthcare provided. Assume also that patients receive some total benefit from care received, reflected by the equation $B(x)=10x - (1/2)x^{2}$. Patients must pay the full price, $p$, of any care received, so that the net benefit of care to the patient is then $B(x)-px$ (their total benefit less their costs). Finally, assume that the best outside option for the patient yields a net benefit of 8.

    + If the patient were to choose $x$ to maximize their net benefit, what level of $x$ would they choose?
    
    + Find the physician's profit maximizing choice of quantity, $x$. You need to solve this as a function of $c$.
    
    + At a marginal cost of $c=2$, find the physician's optimal price, $p$.
    
    + Compare the physician's profit maximizing choice of $x$ to the patient's optimal choice of $x$. Are these the same? Why or why not?


2. Assume instead that the physician faces a fixed price, $\bar{p}=4$. The setup is otherwise identical to question 1.

    + If the patient were to choose $x$ to maximize their net benefit, what level of $x$ would they choose?
    
    + Again assuming $c=2$, find the physician's profit maximizing choice of quantity, $x$. Hint: marginal cost doesn't matter here except to ensure that $c<\bar{p}$.
    
    + How does the deviation in the physician and patient optima differ from what you found in question 1? Explain your answer in a couple of sentences.


3. Assume now that the physician can affect the number of their patients through their influence on the net benefit (NB) provided to patients. Assume also that the physician faces a fixed price paid by the insurer, denoted $p_{s}$, along with a capitated payment per patient, $R$, and that the patient faces a price of <span>&#36;</span>0, $p_{d}=0$. In this extension, the physician's goal is to choose $x$ so as to maximize profit, $$\pi = n\left(NB\right) \left[R + (p_{s}-c)x \right].$$ Finally, assume the functional forms $n(NB)=\sqrt{NB}$ and $B(x)=10x-x^{2}$.

    + Find the patient's optimal level of $x$.
    
    + Find the first order condition for the physician's choice of $x$. Don't try to solve this for $x$.
    
    + Assuming that the physician makes <span>&#36;</span>1 on each quantity of care provided ($p_{s}-c=1$), find the value of the capitated payment, $R$, such that overtreatment is minimized. Please assume that $x$ can only take discrete values, so that the minimum amount of overtreatment is 1 "unit of care" per patient.
    
    + Assuming that the physician loses <span>&#36;</span>1 on each quantity of care provided ($p_{s}-c=-1$), find the value of the capitated payment, $R$, such that undertreatment is minimized. Again, assume that $x$ can only take discrete values, so that the minimum amount of undertreatment is 1 "unit of care" per patient.
    
    + Which scenario (minimizing overtreatment or undertreatment) is better for the physician's profit.

    
## Empirical Questions

4. In January 2014, CMS reduced it's payments to physicians for epidural steroidal injections (CPT codes 62310, 62311, 62318, and 62319). The reduction was part of an effort to adjust "potentially misvalued services," in which CMS lowered the payment rates back to 2013 levels. CMS subsequently increased the payment levels in 2015. Talk about whiplash! For this question, we're going to use the Medicare Provider Utilization and Payment Data from 2013 through 2015 to see how these payment changes may have affected the frequency of epidural steroidal injections. These data are available on our **Canvas** page...just look for the **Data** section on the main landing page. Take a look at the data in your favorite software, and answer the following questions:

    + How many unique physicians administered at least one epidural steroidal injection in 2013?
    
    + Among those physicians, what was the average number of injections in each year (2013 through 2015)? Use a graph to support your answer.
    
    + Among physicians with some injections in both 2013 and 2014, identify the physicians with the 10 largest reductions in injections from 2013 to 2014 (i.e., I want to see the physicians with the largest reductions, but exclude physicians that dropped to 0).
    
    + For the physicians identified in part 3, plot the number of injections for each physician over time (scatter plot with the count of injections on the vertical axis and year on the horizontal axis).
    
    + Take a look at this report on steroidal pain injections for low back pain, [here](https://www.cms.gov/Medicare/Coverage/DeterminationProcess/Downloads/id98TA.pdf). In light of this report, revisit some of your emprical work specifically for low back pain and explain your findings in the context of the physician agency problem. **CORRECTION** the link I provided has since been removed or changed. Plus, I condensed these data to make them easier to work with, and in doing so, I removed the information you would need to identify low back pain treatments. Therefore, everyone can skip this part of the question. You'll all receive full credit since you can't do this problem. Sorry about that!
    

5. In January 2021, CMS changed its physician fee schedule, instituting relatively large increases for "Evaluation and Management" (E&M, or just office visits) codes. **But**, due to budget neutrality requirements, such an increase required an offset for other services. Therefore, CMS also lowered the overall "conversion factor". This made more expensive services in 2020 relatively less profitable, while payments for otherwise less expensive services were less affected (E&M services, of course, actually increased in payment rate). For a decent discussion of these issues, see [here](https://www.jtaylor.com/news/on-december-1-2020-the-centers-for-medicare-and-medicaid). For this question, we're going to again work with the Medicare Provider Utilization and Payment Data available on **Canvas**. We'll focus just on the 2018 data since data from 2020 and 2021 aren't available yet. We'll also focus only on physicians in Georgia because the full data is a little too much to manage for this assignment.

    + Identify a set of HCPCS codes that capture physician office visits. Do some internet digging first, just to see if you can find the codes that way. Ultimately, the best strategy is probably to identify the relevant codes based on the observed descriptions in the data.
    
    + Identify the physicians with the most (top 10) E&M visits in 2018.
    
    + How much would these physicians from part b (the top 10 physicians) stand to gain from the increased RVU rate? Show your results in a table.
    
    + In the context of physician agency, what might you predict will happen to utilization of more expensive services after the 2021 fee schedule update?