---
title: "Final Project"
linktitle: "Final project"
due_date: "2021-05-12"
due_time: "11:59 PM"
output:
  blogdown::html_page:
    toc: false
menu:
  assignment:
    parent: Project
    weight: 1
type: docs
---
The final project is a big part of your grade. This essentially replaces what would otherwise be a final exam. Please start as early as possible and save yourself lots of stress in May!


## Overview
Hospital price transparency is an important topic and one that has been at the forefront of health policy debates for many years. Recently (like just now!), CMS mandated that hospitals provide their negotiated payment rates in a "machine-readable" format for patients to be able to see actual hospital prices for selected procedures. For more info on the initiative, see [here](https://www.cms.gov/hospital-price-transparency). 

Building off of this new policy, this project is all about hospital "prices". There are three main elements of the project:

1. Collect data on hospital prices, charges, and Medicare payment rates for select procedures
2. Discuss the differences between these different measures of "price"
3. Examine the implications of a "charge-based" pricing contract versus a "Medicare-based" pricing contract. 

## Project Details {#steps}
Your project analysis should proceed with the following steps:

1. Identify a hospital market in the U.S. that you would like to study. You can find a list of hospital markets on the shared Google Sheet, [econ372-hospital-markets](https://docs.google.com/spreadsheets/d/1uMsKWUxqYZb_JAx54A9tpK0pREnVLKf3Xv-vuLuCmkY/edit?usp=sharing), on the **Markets** tab. Put your name by the market you'd like to study. 

**UPDATE:** Hospitals have made it very hard to find the information you need, and many hospitals don't present this information in any meaningful way. So, rather than each student selecting their own market to study, you can instead select from a list of markets in which I know the necessary data are available from a sufficient number of hospitals. These markets include (more markets may be added over time):
  - Indianapolis, IN
  - Miami, FL
  - Chicago, IL
  - Atlanta, GA

Select the market you'd like to study and identify at least 3 hospitals from at least 2 different systems in that market that you will focus on for this project. You can look at the **Hospitals** on the Google Sheet to find a list of possible hospitals; however, this list is not comprehensive as it is a master list based on data in 2018, and some hospitals have opened or changed since then. 

Once you've selected a market and at least 3 hospitals, note these hospitals, the markets, and your name in the **Final Selections* tab of our Google Sheet. List these hospitals along with a brief description of each hospital in the first section of your paper. For example, is the hospital a specialty hospital, or does it have any reputation that you're aware of as a "good" or "bad" hospital in some area?

2. Collect data on the hospitals' charges and negotiated prices. These may be difficult to find, and the data will likely be in different formats across different hospitals. Once you've found the data, paste the link to the file in our [econ372-hospital-markets](https://docs.google.com/spreadsheets/d/1uMsKWUxqYZb_JAx54A9tpK0pREnVLKf3Xv-vuLuCmkY/edit?usp=sharing) Google Sheet on the **Final Selections** tab. Be sure to paste the specific link for each hospital (not just one link for a whole market). Here are a couple of hints to help you find these links:

    + According to the CMS final rule files for the price transparency initiative, all of the new pricing files should follow the same naming convention, `<ein>_<hospital-name>_standardcharges.[json|xml|csv]`. `ein` stands for Employer Identification Number. **Note:** Not all hospitals follow this naming convention, so it may take some time to find the right files.
    + Google has several advanced search options that allow you to find all sorts of very specific files. For example, if you wanted to find pdf files linked in a certain url, you would type `filetype:pdf inurl: <url>` directly into the search bar. This will give you a list of results for the links to pdf files within the specific url you provided. **Note:** Google might think you're a robot with these types of searches, so be ready to prove otherwise.

3. Collect data on Medicare payment rates for the same hospitals and same procedures. These data are publicly available from the [Medicare Provider Utilization and Payment Data: Inpatient](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Provider-Charge-Data/Inpatient) files. Focus on the 2018 data, since that's the most recent data available.

4. Create a dataset that contains data from 2 and 3. In these data, each row should be a hospital/procedure pair, and the columns should include information such as: "hospital ID"; "DRG code"; "Total discharges"; "gross charge"; "negotiated payment"; and "Medicare payment". Save your dataset as a ".csv" file and include it as part of your project submission.

5. Provide a table of summary values for each hospital. For example, your table could show the mean charge and payments for these procedures by hospital. 

6. Calculate the range of charges, negotiated prices, and Medicare payments *across hospitals* in your market. Show these ranges in a figure.

7. Highlight one interesting aspect of your data and discuss this in your report. Support your discussion with at least one figure or table. You get to choose what is "interesting" here. Think of this as summarizing your findings from Q2-Q6 above.

8. Now let's think about how these pricing figures relate to competition. Calculate each hospital's market share and provide a scatterplot of the market share and negotiated payments. Pick whatever procedure you'd like to focus on. In your figure, please highlight the different hospitals in some way (e.g., use different colors for each hospital or different shapes for each plot). 

9. What do you take from these data? Does it seem as if the larger or more powerful hospital has a higher price? Relate these findings to the bargaining model we covered in class, focusing in particular on the notion of the insurer and hospital's outside options. Support your conclusions with at least one peer-reviewed academic paper.

10. Now let's think about contracts. For each hospital in your data, try to determine whether their negotiated prices are more similar to "markup over Medicare" or "percentage of charges". Explain your conclusion and support your determination with a figure or a table. How does this conclusion relate to the hospital's market power?

11. Finally, go find some measure of quality for each hospital. Ideally, these quality measures would be specific to each procedure, but that's likely not possible, so any hospital-level measure of quality will do. This could be patient ratings on Google Reviews, or it could be [official hospital quality measures](https://qualitynet.cms.gov/inpatient/public-reporting/overall-ratings) from CMS. How do the hospital prices correlate with these quality measues (do they seem to be positively or negatively correlated)? Support your conclusions with at least one peer-reviewed academic paper.

12. Given your analysis and your experience collecting these data, do you think the price transparency initiative will help to reduce hospital prices? Why or why not?

13. Reflect on your work. Describe one thing you learned from this process and one area that left you confused or unclear. 

## Formatting and Report Structure {#format}
As with your homework assignments and exam, you will turn in your project via *Canvas*. Your final project must meet the following basic formatting requirements: 

- **Format**: Double-spaced text with clearly defined section headings and subheadings
- **Length**: At least 5 and no more than 10 pages, excluding references, tables, or figures
- **Citations**: At least 3 peer-reviewed academic journal articles
- **Data Visualization**: At least two tables and two figures 

Please organize your final report along the following sections:

1. **Description of your selected market and hospitals**: Relates to Q1 in [Project Details](#steps)
2. **Hospital prices, charges, and Medicare payments**: Relates to Q2-Q7 in [Project Details](#steps)
3. **Pricing and competition**: Relates to Q8-Q10 in [Project Details](#steps)
4. **Pricing and quality**: Relates to Q11 in [Project Details](#steps)
5. **Summary and conclusions**: Relates to Q12-Q13 in [Project Details](#steps)


## Grading Criteria
Your final project grade is based off of 140 points as allocated below. Components worth 5 points will be graded in single point increments. All other components will be graded in 5 point increments. For example, the "Discussion of Payments" component can receive credit of 0, 5, 10, or 15 points. This rubric is designed to ensure grading is fair across all students, as it is nearly impossible to discern single-point differences in credit for long-answer questions.

- **Follow instructions** (10 points): Does your report meet the requirements for length, formatting, citations, and data visualization?
- **Grammar** (5 points): Does your report have sufficiently few grammatical mistakes, typos, etc.?
- **Pricing data** (5 points): Did you provide the link to the pricing data in our Google Sheet as described in Q2 in [Project Details](#steps)? **UPDATE:** Many of you may select the same hospitals and therefore have the same links. That's OK. I still want everyone to post their own link in the **Final Selections* tab of our Google Sheet.
- **Complete data** (15 points): Did you create and submit the final dataset as described in Q4 in [Project Details](#steps)?
- **Data summary** (20 points): Did you summarize your data as described in Q5 and Q6 in [Project Details](#steps)?
- **Discussion of payments** (15 points): Did you discuss your pricing data as describe in Q7 in [Project Details](#steps)?
- **Competition data** (15 points): Did you incorporate and summarize data on hospital market power and prices as described in Q8 in [Project Details](#steps)?
- **Discussion of competition** (10 points): Did you discuss your findings related to competition and prices as described in Q9 in [Project Details](#steps)?
- **Competition and contracts** (15 points): Did you try to determine the type of contract that the hospitals appear to have negotiated as described in Q10 in [Project Details](#steps)?
- **Quality and pricing** (10 points): Did you incorporate quality information and discuss those data as described in Q11 in [Project Details](#steps)?
- **Conclusion** (10 points): Did you relate your findings to the price transparency initiative as described in Q12 in [Project Details](#steps)?
- **Reflection** (15 points): Did you reflect on your work as described in Q13 in [Project Details](#steps)?
- **Bonus**: Provide additional links to the pricing data in the **Hospitals** tab of the Google Sheet. You'll receive 1 extra point for every extra link you provide (up to 5 additional links).